# Generated by Django 5.2.15 on 2026-06-16 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0002_load_color_belt_exam_templates'),
    ]

    operations = [
        migrations.AddField(
            model_name='examen',
            name='es_historico',
            field=models.BooleanField(default=False),
        ),
    ]
