# Generated by Django 5.2.15 on 2026-06-21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alumnos", "0003_add_historical_exam_flag"),
    ]

    operations = [
        migrations.AddField(
            model_name="alumno",
            name="fecha_inicio_taekwondo",
            field=models.DateField(
                blank=True,
                help_text="Fecha en la que comenzó a practicar Taekwondo.",
                null=True,
            ),
        ),
    ]
