# Generated by Django 5.2.15 on 2026-06-21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("alumnos", "0004_alumno_fecha_inicio_taekwondo"),
    ]

    operations = [
        migrations.AddField(
            model_name="examentemplate",
            name="template_origen",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="versiones_derivadas",
                to="alumnos.examentemplate",
            ),
        ),
        migrations.AddField(
            model_name="examentemplate",
            name="vigente_desde",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="examentemplate",
            name="vigente_hasta",
            field=models.DateField(blank=True, null=True),
        ),
    ]
