# Generated by Django 5.2.15 on 2026-06-23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("alumnos", "0005_examentemplate_versionado"),
        ("escuelas", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AlumnoEscuela",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("activo", models.BooleanField(default=True)),
                ("fecha_inscripcion", models.DateField(auto_now_add=True)),
                ("fecha_baja", models.DateField(blank=True, null=True)),
                ("observaciones", models.TextField(blank=True, null=True)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_modificacion", models.DateTimeField(auto_now=True)),
                ("alumno", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="inscripciones_escuela", to="alumnos.alumno")),
                ("escuela", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="alumnos_inscriptos", to="escuelas.escuela")),
            ],
            options={"verbose_name": "Inscripción de alumno", "verbose_name_plural": "Inscripciones de alumnos", "ordering": ["-activo", "alumno__apellido", "alumno__nombre"]},
        ),
        migrations.AddConstraint(
            model_name="alumnoescuela",
            constraint=models.UniqueConstraint(fields=("alumno", "escuela"), name="uq_alumno_escuela"),
        ),
    ]
