# Generated by Django 5.2.15 on 2026-06-23

from django.db import migrations


def crear_escuela_e_inscripciones(apps, schema_editor):
    Escuela = apps.get_model("escuelas", "Escuela")
    Alumno = apps.get_model("alumnos", "Alumno")
    AlumnoEscuela = apps.get_model("alumnos", "AlumnoEscuela")

    escuela, _ = Escuela.objects.get_or_create(
        nombre="TAEB Escuela Principal", defaults={"activo": True}
    )
    for alumno in Alumno.objects.all().iterator():
        inscripcion, creada = AlumnoEscuela.objects.get_or_create(
            alumno=alumno,
            escuela=escuela,
            defaults={"activo": alumno.activo},
        )
        if creada:
            inscripcion.fecha_inscripcion = alumno.fecha_creacion.date()
            inscripcion.save(update_fields=["fecha_inscripcion"])


class Migration(migrations.Migration):

    dependencies = [
        ("alumnos", "0006_alumnoescuela"),
    ]

    operations = [
        migrations.RunPython(crear_escuela_e_inscripciones, migrations.RunPython.noop),
    ]
