# Generated by Django 5.2.15 on 2026-08-25 22:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0008_alumnocredencial'),
        ('escuelas', '0002_alter_escueladocente_docente_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='cinturon_actual',
            field=models.ForeignKey(blank=True, db_column='id_cinturon_actual', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='alumnos_actuales', to='alumnos.cinturon'),
        ),
        migrations.AlterField(
            model_name='alumnocinturonhistorial',
            name='alumno',
            field=models.ForeignKey(db_column='id_alumno', on_delete=django.db.models.deletion.PROTECT, related_name='historial_cinturones', to='alumnos.alumno'),
        ),
        migrations.AlterField(
            model_name='alumnocinturonhistorial',
            name='cinturon',
            field=models.ForeignKey(db_column='id_cinturon', on_delete=django.db.models.deletion.PROTECT, related_name='historial_alumnos', to='alumnos.cinturon'),
        ),
        migrations.AlterField(
            model_name='alumnocinturonhistorial',
            name='examen',
            field=models.OneToOneField(blank=True, db_column='id_examen', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='historial_cinturon', to='alumnos.examen'),
        ),
        migrations.AlterField(
            model_name='alumnocredencial',
            name='alumno',
            field=models.OneToOneField(db_column='id_alumno', on_delete=django.db.models.deletion.PROTECT, related_name='credencial_mobile', to='alumnos.alumno'),
        ),
        migrations.AlterField(
            model_name='alumnocredencial',
            name='usuario',
            field=models.OneToOneField(db_column='id_usuario', on_delete=django.db.models.deletion.PROTECT, related_name='credencial_alumno', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='alumnoescuela',
            name='alumno',
            field=models.ForeignKey(db_column='id_alumno', on_delete=django.db.models.deletion.PROTECT, related_name='inscripciones_escuela', to='alumnos.alumno'),
        ),
        migrations.AlterField(
            model_name='alumnoescuela',
            name='escuela',
            field=models.ForeignKey(db_column='id_escuela', on_delete=django.db.models.deletion.PROTECT, related_name='alumnos_inscriptos', to='escuelas.escuela'),
        ),
        migrations.AlterField(
            model_name='examen',
            name='alumno',
            field=models.ForeignKey(db_column='id_alumno', on_delete=django.db.models.deletion.PROTECT, related_name='examenes', to='alumnos.alumno'),
        ),
        migrations.AlterField(
            model_name='examen',
            name='cinturon_destino',
            field=models.ForeignKey(db_column='id_cinturon_destino', on_delete=django.db.models.deletion.PROTECT, related_name='examenes_destino', to='alumnos.cinturon'),
        ),
        migrations.AlterField(
            model_name='examen',
            name='cinturon_origen',
            field=models.ForeignKey(db_column='id_cinturon_origen', on_delete=django.db.models.deletion.PROTECT, related_name='examenes_origen', to='alumnos.cinturon'),
        ),
        migrations.AlterField(
            model_name='examen',
            name='examen_template',
            field=models.ForeignKey(db_column='id_plantilla', on_delete=django.db.models.deletion.PROTECT, related_name='examenes', to='alumnos.examentemplate'),
        ),
        migrations.AlterField(
            model_name='examendetalle',
            name='examen',
            field=models.ForeignKey(db_column='id_examen', on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='alumnos.examen'),
        ),
        migrations.AlterField(
            model_name='examendetalle',
            name='template_item',
            field=models.ForeignKey(db_column='id_plantilla_item', on_delete=django.db.models.deletion.PROTECT, related_name='detalles_examen', to='alumnos.examentemplateitem'),
        ),
        migrations.AlterField(
            model_name='examentemplate',
            name='cinturon',
            field=models.ForeignKey(db_column='id_cinturon', on_delete=django.db.models.deletion.PROTECT, related_name='templates_examen', to='alumnos.cinturon'),
        ),
        migrations.AlterField(
            model_name='examentemplate',
            name='template_origen',
            field=models.ForeignKey(blank=True, db_column='id_plantilla_origen', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='versiones_derivadas', to='alumnos.examentemplate'),
        ),
        migrations.AlterField(
            model_name='examentemplateitem',
            name='seccion',
            field=models.ForeignKey(db_column='id_seccion', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='alumnos.examentemplateseccion'),
        ),
        migrations.AlterField(
            model_name='examentemplateseccion',
            name='examen_template',
            field=models.ForeignKey(db_column='id_plantilla', on_delete=django.db.models.deletion.CASCADE, related_name='secciones', to='alumnos.examentemplate'),
        ),
        migrations.AlterModelTable(
            name='alumno',
            table='alumnos',
        ),
        migrations.AlterModelTable(
            name='alumnocinturonhistorial',
            table='alumnos_cinturones_historial',
        ),
        migrations.AlterModelTable(
            name='alumnocredencial',
            table='alumnos_credenciales',
        ),
        migrations.AlterModelTable(
            name='alumnoescuela',
            table='alumnos_escuelas',
        ),
        migrations.AlterModelTable(
            name='cinturon',
            table='alumnos_cinturones',
        ),
        migrations.AlterModelTable(
            name='examen',
            table='alumnos_examenes',
        ),
        migrations.AlterModelTable(
            name='examendetalle',
            table='alumnos_examenes_detalles',
        ),
        migrations.AlterModelTable(
            name='examentemplate',
            table='alumnos_examenes_plantillas',
        ),
        migrations.AlterModelTable(
            name='examentemplateitem',
            table='alumnos_examenes_plantillas_items',
        ),
        migrations.AlterModelTable(
            name='examentemplateseccion',
            table='alumnos_examenes_plantillas_secciones',
        ),
    ]
