# Generated by Django 5.2.15 on 2026-06-23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("usuarios", "0001_docente"),
    ]

    operations = [
        migrations.CreateModel(
            name="Escuela",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("nombre", models.CharField(max_length=150)),
                ("nombre_comercial", models.CharField(blank=True, max_length=150, null=True)),
                ("razon_social", models.CharField(blank=True, max_length=150, null=True)),
                ("cuit", models.CharField(blank=True, max_length=20, null=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("telefono", models.CharField(blank=True, max_length=30, null=True)),
                ("direccion", models.CharField(blank=True, max_length=255, null=True)),
                ("ciudad", models.CharField(blank=True, max_length=100, null=True)),
                ("provincia", models.CharField(blank=True, max_length=100, null=True)),
                ("activo", models.BooleanField(default=True)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_modificacion", models.DateTimeField(auto_now=True)),
            ],
            options={"verbose_name": "Escuela", "verbose_name_plural": "Escuelas", "ordering": ["nombre"]},
        ),
        migrations.CreateModel(
            name="EscuelaDocente",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("rol", models.CharField(choices=[("ADMINISTRADOR", "Administrador"), ("DOCENTE", "Docente"), ("COORDINADOR", "Coordinador")], default="DOCENTE", max_length=20)),
                ("activo", models.BooleanField(default=True)),
                ("fecha_alta", models.DateField(auto_now_add=True)),
                ("fecha_baja", models.DateField(blank=True, null=True)),
                ("docente", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="escuelas", to="usuarios.docente")),
                ("escuela", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="docentes", to="escuelas.escuela")),
            ],
            options={"verbose_name": "Asignación de docente", "verbose_name_plural": "Asignaciones de docentes", "ordering": ["fecha_alta", "pk"]},
        ),
        migrations.AddConstraint(
            model_name="escueladocente",
            constraint=models.UniqueConstraint(fields=("escuela", "docente"), name="uq_escuela_docente"),
        ),
    ]
