# Generated by Django 5.2.15 on 2026-08-25 22:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escuelas', '0001_initial'),
        ('usuarios', '0002_alter_docente_usuario_alter_docente_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escueladocente',
            name='docente',
            field=models.ForeignKey(db_column='id_docente', on_delete=django.db.models.deletion.PROTECT, related_name='escuelas', to='usuarios.docente'),
        ),
        migrations.AlterField(
            model_name='escueladocente',
            name='escuela',
            field=models.ForeignKey(db_column='id_escuela', on_delete=django.db.models.deletion.PROTECT, related_name='docentes', to='escuelas.escuela'),
        ),
        migrations.AlterModelTable(
            name='escuela',
            table='escuelas',
        ),
        migrations.AlterModelTable(
            name='escueladocente',
            table='escuelas_docentes',
        ),
    ]
