# Generated by Django 5.2.15 on 2026-08-26 00:56

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alumnos', '0009_alter_alumno_cinturon_actual_and_more'),
        ('escuelas', '0002_alter_escueladocente_docente_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConceptoFinanciero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(choices=[('CUOTA', 'Cuota'), ('EXAMEN', 'Examen'), ('TORNEO', 'Torneo')], max_length=20)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('escuela', models.ForeignKey(db_column='id_escuela', on_delete=django.db.models.deletion.PROTECT, related_name='conceptos_financieros', to='escuelas.escuela')),
            ],
            options={
                'db_table': 'finanzas_conceptos',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='ConfiguracionCuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_actual', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('dia_vencimiento', models.PositiveSmallIntegerField(default=10, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(28)])),
                ('dias_tolerancia', models.PositiveSmallIntegerField(default=0)),
                ('activa', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('escuela', models.OneToOneField(db_column='id_escuela', on_delete=django.db.models.deletion.PROTECT, related_name='configuracion_cuota', to='escuelas.escuela')),
            ],
            options={
                'db_table': 'finanzas_configuraciones_cuota',
            },
        ),
        migrations.CreateModel(
            name='ObligacionPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255)),
                ('monto_original', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('periodo_anio', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('periodo_mes', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('fecha_generacion', models.DateField()),
                ('fecha_vencimiento', models.DateField()),
                ('fecha_atraso', models.DateField()),
                ('clave_origen', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('estado_operativo', models.CharField(choices=[('ACTIVA', 'Activa'), ('ANULADA', 'Anulada')], default='ACTIVA', max_length=10)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('alumno_escuela', models.ForeignKey(db_column='id_alumno_escuela', on_delete=django.db.models.deletion.PROTECT, related_name='obligaciones_pago', to='alumnos.alumnoescuela')),
                ('concepto_financiero', models.ForeignKey(db_column='id_concepto_financiero', on_delete=django.db.models.deletion.PROTECT, related_name='obligaciones', to='finanzas.conceptofinanciero')),
                ('creado_por', models.ForeignKey(db_column='id_usuario_creacion', on_delete=django.db.models.deletion.PROTECT, related_name='obligaciones_creadas', to=settings.AUTH_USER_MODEL)),
                ('escuela', models.ForeignKey(db_column='id_escuela', on_delete=django.db.models.deletion.PROTECT, related_name='obligaciones_pago', to='escuelas.escuela')),
            ],
            options={
                'db_table': 'finanzas_obligaciones',
                'ordering': ['-fecha_generacion', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('metodo_pago', models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TRANSFERENCIA', 'Transferencia')], max_length=20)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('CONFIRMADO', 'Confirmado'), ('ANULADO', 'Anulado')], default='CONFIRMADO', max_length=12)),
                ('fecha_pago', models.DateField()),
                ('referencia', models.CharField(blank=True, max_length=150, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('alumno_escuela', models.ForeignKey(db_column='id_alumno_escuela', on_delete=django.db.models.deletion.PROTECT, related_name='pagos', to='alumnos.alumnoescuela')),
                ('escuela', models.ForeignKey(db_column='id_escuela', on_delete=django.db.models.deletion.PROTECT, related_name='pagos', to='escuelas.escuela')),
                ('registrado_por', models.ForeignKey(db_column='id_usuario_registro', on_delete=django.db.models.deletion.PROTECT, related_name='pagos_registrados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'finanzas_pagos',
                'ordering': ['-fecha_pago', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='PagoAplicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_aplicado', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('obligacion_pago', models.ForeignKey(db_column='id_obligacion_pago', on_delete=django.db.models.deletion.PROTECT, related_name='aplicaciones_pago', to='finanzas.obligacionpago')),
                ('pago', models.ForeignKey(db_column='id_pago', on_delete=django.db.models.deletion.PROTECT, related_name='aplicaciones', to='finanzas.pago')),
            ],
            options={
                'db_table': 'finanzas_pagos_aplicaciones',
            },
        ),
        migrations.AddConstraint(
            model_name='conceptofinanciero',
            constraint=models.UniqueConstraint(fields=('escuela', 'codigo'), name='uq_finanzas_concepto_escuela_codigo'),
        ),
        migrations.AddIndex(
            model_name='obligacionpago',
            index=models.Index(fields=['escuela', 'periodo_anio', 'periodo_mes'], name='idx_fin_oblig_periodo'),
        ),
        migrations.AddConstraint(
            model_name='pagoaplicacion',
            constraint=models.UniqueConstraint(fields=('pago', 'obligacion_pago'), name='uq_finanzas_pago_obligacion'),
        ),
    ]
