# Generated by Django 5.2.15 on 2026-06-23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Docente",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("dni", models.CharField(max_length=20, unique=True)),
                ("telefono", models.CharField(blank=True, max_length=30, null=True)),
                ("fecha_nacimiento", models.DateField(blank=True, null=True)),
                ("activo", models.BooleanField(default=True)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_modificacion", models.DateTimeField(auto_now=True)),
                ("usuario", models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name="perfil_docente", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "verbose_name": "Docente",
                "verbose_name_plural": "Docentes",
                "ordering": ["usuario__last_name", "usuario__first_name", "usuario__username"],
            },
        ),
    ]
