# Generated by Django 5.2.15 on 2026-08-25 22:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_docente'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='docente',
            name='usuario',
            field=models.OneToOneField(db_column='id_usuario', on_delete=django.db.models.deletion.PROTECT, related_name='perfil_docente', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterModelTable(
            name='docente',
            table='usuarios_docentes',
        ),
    ]
