# Generated by Django 5.2.15 on 2026-07-01 02:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alumnos', '0007_inscribir_alumnos_escuela_principal'),
        ('escuelas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Clase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('cupo_maximo', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('docente_responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='clases_responsables', to='escuelas.escueladocente')),
                ('escuela', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clases', to='escuelas.escuela')),
            ],
            options={
                'verbose_name': 'Clase',
                'verbose_name_plural': 'Clases',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='ClaseAlumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True)),
                ('fecha_alta', models.DateField(auto_now_add=True)),
                ('fecha_baja', models.DateField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('alumno_escuela', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clases_inscriptas', to='alumnos.alumnoescuela')),
                ('clase', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inscripciones_alumnos', to='clases.clase')),
            ],
            options={
                'verbose_name': 'Inscripcion a clase',
                'verbose_name_plural': 'Inscripciones a clases',
                'ordering': ['-activo', 'alumno_escuela__alumno__apellido'],
            },
        ),
        migrations.CreateModel(
            name='ClaseHorario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.PositiveSmallIntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miercoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sabado'), (6, 'Domingo')])),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('fecha_desde', models.DateField(blank=True, null=True)),
                ('fecha_hasta', models.DateField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('clase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='clases.clase')),
            ],
            options={
                'verbose_name': 'Horario de clase',
                'verbose_name_plural': 'Horarios de clases',
                'ordering': ['dia_semana', 'hora_inicio'],
            },
        ),
        migrations.CreateModel(
            name='ClaseSesion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('estado', models.CharField(choices=[('PROGRAMADA', 'Programada'), ('EN_CURSO', 'En curso'), ('FINALIZADA', 'Finalizada'), ('CANCELADA', 'Cancelada')], default='PROGRAMADA', max_length=15)),
                ('es_clase_extra', models.BooleanField(default=False)),
                ('motivo_cancelacion', models.TextField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('clase', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sesiones', to='clases.clase')),
                ('docente_a_cargo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sesiones_a_cargo', to='escuelas.escueladocente')),
                ('horario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sesiones', to='clases.clasehorario')),
            ],
            options={
                'verbose_name': 'Sesion de clase',
                'verbose_name_plural': 'Sesiones de clases',
                'ordering': ['fecha', 'hora_inicio'],
            },
        ),
        migrations.CreateModel(
            name='AsistenciaClase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PRESENTE', 'Presente'), ('AUSENTE', 'Ausente'), ('JUSTIFICADA', 'Ausencia justificada'), ('TARDE', 'Llego tarde')], default='PENDIENTE', max_length=15)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='asistencias_registradas', to=settings.AUTH_USER_MODEL)),
                ('clase_alumno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asistencias', to='clases.clasealumno')),
                ('sesion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asistencias', to='clases.clasesesion')),
            ],
            options={
                'verbose_name': 'Asistencia de clase',
                'verbose_name_plural': 'Asistencias de clases',
                'ordering': ['clase_alumno__alumno_escuela__alumno__apellido'],
            },
        ),
        migrations.AddConstraint(
            model_name='clase',
            constraint=models.UniqueConstraint(fields=('escuela', 'nombre'), name='uq_clase_escuela_nombre'),
        ),
        migrations.AddConstraint(
            model_name='clasealumno',
            constraint=models.UniqueConstraint(fields=('clase', 'alumno_escuela'), name='uq_clase_alumno'),
        ),
        migrations.AddConstraint(
            model_name='clasehorario',
            constraint=models.UniqueConstraint(fields=('clase', 'dia_semana', 'hora_inicio'), name='uq_clase_horario'),
        ),
        migrations.AddConstraint(
            model_name='clasesesion',
            constraint=models.UniqueConstraint(fields=('clase', 'fecha', 'hora_inicio'), name='uq_clase_sesion_fecha_hora'),
        ),
        migrations.AddConstraint(
            model_name='asistenciaclase',
            constraint=models.UniqueConstraint(fields=('sesion', 'clase_alumno'), name='uq_asistencia_sesion_alumno'),
        ),
    ]
