# Generated by Django 5.2.15 on 2026-08-25 22:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0009_alter_alumno_cinturon_actual_and_more'),
        ('clases', '0001_initial'),
        ('escuelas', '0002_alter_escueladocente_docente_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistenciaclase',
            name='clase_alumno',
            field=models.ForeignKey(db_column='id_clase_alumno', on_delete=django.db.models.deletion.PROTECT, related_name='asistencias', to='clases.clasealumno'),
        ),
        migrations.AlterField(
            model_name='asistenciaclase',
            name='registrado_por',
            field=models.ForeignKey(blank=True, db_column='id_usuario_registro', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='asistencias_registradas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='asistenciaclase',
            name='sesion',
            field=models.ForeignKey(db_column='id_sesion', on_delete=django.db.models.deletion.PROTECT, related_name='asistencias', to='clases.clasesesion'),
        ),
        migrations.AlterField(
            model_name='clase',
            name='docente_responsable',
            field=models.ForeignKey(blank=True, db_column='id_docente_responsable', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='clases_responsables', to='escuelas.escueladocente'),
        ),
        migrations.AlterField(
            model_name='clase',
            name='escuela',
            field=models.ForeignKey(db_column='id_escuela', on_delete=django.db.models.deletion.PROTECT, related_name='clases', to='escuelas.escuela'),
        ),
        migrations.AlterField(
            model_name='clasealumno',
            name='alumno_escuela',
            field=models.ForeignKey(db_column='id_alumno_escuela', on_delete=django.db.models.deletion.PROTECT, related_name='clases_inscriptas', to='alumnos.alumnoescuela'),
        ),
        migrations.AlterField(
            model_name='clasealumno',
            name='clase',
            field=models.ForeignKey(db_column='id_clase', on_delete=django.db.models.deletion.PROTECT, related_name='inscripciones_alumnos', to='clases.clase'),
        ),
        migrations.AlterField(
            model_name='clasehorario',
            name='clase',
            field=models.ForeignKey(db_column='id_clase', on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='clases.clase'),
        ),
        migrations.AlterField(
            model_name='clasesesion',
            name='clase',
            field=models.ForeignKey(db_column='id_clase', on_delete=django.db.models.deletion.PROTECT, related_name='sesiones', to='clases.clase'),
        ),
        migrations.AlterField(
            model_name='clasesesion',
            name='docente_a_cargo',
            field=models.ForeignKey(blank=True, db_column='id_docente_a_cargo', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sesiones_a_cargo', to='escuelas.escueladocente'),
        ),
        migrations.AlterField(
            model_name='clasesesion',
            name='horario',
            field=models.ForeignKey(blank=True, db_column='id_horario', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sesiones', to='clases.clasehorario'),
        ),
        migrations.AlterModelTable(
            name='asistenciaclase',
            table='clases_asistencias',
        ),
        migrations.AlterModelTable(
            name='clase',
            table='clases',
        ),
        migrations.AlterModelTable(
            name='clasealumno',
            table='clases_alumnos',
        ),
        migrations.AlterModelTable(
            name='clasehorario',
            table='clases_horarios',
        ),
        migrations.AlterModelTable(
            name='clasesesion',
            table='clases_sesiones',
        ),
    ]
